sudo: required

services:
  - docker

language: python

python:
  - "2.7"

env:
  matrix:
    - ROS_DISTRO=hydro ROS_PARALLEL_JOBS="-j2 -l2"
    - ROS_DISTRO=indigo ROS_PARALLEL_JOBS="-j8"
    - ROS_DISTRO=jade ROS_PARALLEL_JOBS="-j8"

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull "magiclab/ros:${ROS_DISTRO}" || true

script:
  - docker build -t "magiclab/ros:${ROS_DISTRO}" - < "ros-base:${ROS_DISTRO}.dockerfile"

after_success:
  - docker push "magiclab/ros:${ROS_DISTRO}"
